// chat-frontend/src/Components/HeaderComponent/HeaderComponent.tsx
import { connect } from 'react-redux';
import React, { useEffect } from 'react';
import logo from '../../images/logo.png';
import userLogo from '../../images/userLogo.png';
import { store } from '../../Redux/Store';
import socketService from '../../Services/SocketService';
import './HeaderComponent.scss';
import authService from '../../Services/AuthService';

type HeaderProps = {
    configureSocket: any
}
const HeaderComponent = (props: HeaderProps) => {
    authService.checkToken();

    useEffect(() => {
        props.configureSocket();
    })

    const toUserProfile = () => {
        window.location.pathname = '/user-profile';
    };

    const toLibrary = () => {
        window.location.pathname = '/';
    };

    const logout = () => {
        authService.logout();
    };

    return (
        <div className="header">
            <div className="left-part">
                <div className="icon-block">
                    <a href="/">
                        <img src={logo} />
                    </a>
                </div>

                <div className="menu">
                    <div className="menu-item" onClick={() => toLibrary()}>Library</div>
                    <div className="menu-item active">Chat</div>
                </div>
            </div>

            <div className="user-data">
                <p className="userName" onClick={() => toUserProfile()}>{authService.getUserName()}</p>
                <img src={userLogo} width="40px" height="40px" onClick={() => toUserProfile()}></img>
                <p className="logout" onClick={() => logout()}>Exit</p>
            </div>
        </div>
    )
}

const mapDispatchToProps = (dispatch: any) => {
    return{
        configureSocket: () => socketService.configure(dispatch)
    }
}

export default connect(null,mapDispatchToProps) (HeaderComponent);

// library-frontend/src/app/header/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/library-page/services/auth.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  public userLogoLink;

  constructor(private authService: AuthService) { }

  ngOnInit(): void {
    this.userLogoLink = "assets/images/userLogo.png";
  }

  toUserProfile(): void {
    window.location.pathname = '/user-profile';
  }

  logout() : void {
    this.authService.logout();
  }

  getUserName(): string {
    return this.authService.getUserName();
  }
}

<div class="header">
    <div class="left-part">
        <div class="icon-block">
            <a routerLink="/">
                <img src="assets/images/logo.png" />
            </a>
        </div>
        
        <div class="menu">
            <div class="menu-item active">Library</div>
            <div class="menu-item">Chat</div>
        </div>
    </div>

    <div class="user-data">
        <p class="userName" (click)="toUserProfile()">{{ getUserName() }}</p>
        <img src="{{ userLogoLink }}" width="40px" height="40px" (click)="toUserProfile()">
        <p class="logout" (click)="logout()">Exit</p>
    </div>
</div>
